import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionWrapper from "@/lib/SessionWrapper";
import {ThemeProvider} from "@/app/components/theme-provider"
import Nav from "./components/Nav"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
  return (
    <html lang="en">
      <body className={`${inter.className} theme-violet`}>
        <SessionWrapper>
          <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <Nav/>
              {children}
            </ThemeProvider>
        </SessionWrapper>
      </body>
    </html>
  );
}
